export const baseURL = "http://0.0.0.0:8000/api/";
export const registrationEndpoint = baseURL + "auth/registration/";
export const loginEndpoint = baseURL + "auth/login/";
export const get_auth_user = baseURL + "auth/user/";
export const logout_user = baseURL + "auth/logout/";
export const  entry_routes = baseURL + "entries/"
export const  answer_routes = baseURL + "entries/answer"
export const  survey_routes = baseURL + "surveys/"
export const  question_routes = baseURL + "surveys/question"
