# Generated by Django 3.2.15 on 2022-08-26 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0002_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='title',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
