# Generated by Django 3.2.15 on 2022-08-28 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entries', '0001_initial'),
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='surveys.survey'),
        ),
        migrations.AddField(
            model_name='answer',
            name='entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='entries.entry'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='surveys.question'),
        ),
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together={('question', 'entry')},
        ),
    ]
