# Generated by Django 3.2.15 on 2022-08-26 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0002_question'),
        ('entries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='Question',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='surveys.question'),
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
