# Generated by Django 3.2.15 on 2022-08-26 20:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0002_auto_20220826_1939'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='Question',
            new_name='question',
        ),
        migrations.AlterField(
            model_name='answer',
            name='answer',
            field=models.TextField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='entry',
            name='first_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='entry',
            name='last_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
